spring:
  application:
    name: todo-service
  datasource:
    url: jdbc:h2:file:./data/h2-data
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
