CREATE TABLE todo_items
(
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_urls                 VARCHAR(255),
    cloud_forge_console_url VARCHAR(255),
    release_request_url     VARCHAR(255),
    testing_urls            VARCHAR(255),
    completed               BOOL DEFAULT FALSE,
    onenote_url             VARCHAR(255)
);

CREATE TABLE pr_url
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_item_id INT          NOT NULL,
    url          VARCHAR(255) NOT NULL
);

ALTER TABLE pr_url
    ADD CONSTRAINT fk_todo_items_on_pr_url FOREIGN KEY (todo_item_id) REFERENCES todo_items (id);

CREATE TABLE testing_url
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_item_id INT          NOT NULL,
    url          VARCHAR(255) NOT NULL
);

ALTER TABLE testing_url
    ADD CONSTRAINT fk_todo_items_on_testing_url FOREIGN KEY (todo_item_id) REFERENCES todo_items (id);