CREATE TABLE todo_items
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(1000) NOT NULL,
    jira_url                VARCHAR(1000),
    pr_urls                 VARCHAR(10000),
    cloud_forge_console_url VARCHAR(1000),
    release_request_url     VARCHAR(1000),
    testing_urls            VARCHAR(100000),
    completed               BOOL                        DEFAULT FALSE,
    onenote_url             VARCHAR(10000),
    created_on              TIMESTAMP(9) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_on            TIMESTAMP(9) WITH TIME ZONE,
    pi                      VARCHAR(50)   NOT NULL,
    sprint                  int           NOT NULL,
    type                    TINYINT       NOT NULL,
    archived                BOOL                        DEFAULT FALSE
);

CREATE INDEX idx_completed ON todo_items (completed);
CREATE INDEX idx_archived ON todo_items (archived);
CREATE INDEX idx_created_on ON todo_items (created_on);
CREATE INDEX idx_completed_on ON todo_items (completed_on);
CREATE INDEX idx_archived_completed ON todo_items (archived, completed);
CREATE INDEX idx_archived_completed_completed_on ON todo_items (archived, completed, completed_on);
CREATE INDEX idx_archived_completed_created_on ON todo_items (archived, completed, created_on);
CREATE INDEX idx_archived_completed_created_on_completed_on ON todo_items (archived, completed, created_on, completed_on);

CREATE TABLE pr_url
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_item_id BIGINT        NOT NULL,
    url          VARCHAR(1000) NOT NULL
);

ALTER TABLE pr_url
    ADD CONSTRAINT fk_todo_items_on_pr_url FOREIGN KEY (todo_item_id) REFERENCES todo_items (id);

CREATE INDEX idx_pr_url_todo_item_id ON pr_url (todo_item_id);
CREATE INDEX idx_pr_url_url ON pr_url (url);
CREATE INDEX idx_pr_url_todo_item_id_url ON pr_url (todo_item_id, url);

CREATE TABLE testing_url
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_item_id BIGINT         NOT NULL,
    url          VARCHAR(10000) NOT NULL
);

ALTER TABLE testing_url
    ADD CONSTRAINT fk_todo_items_on_testing_url FOREIGN KEY (todo_item_id) REFERENCES todo_items (id);

CREATE INDEX idx_testing_url_todo_item_id ON testing_url (todo_item_id);
CREATE INDEX idx_testing_url_url ON testing_url (url);
CREATE INDEX idx_testing_url_todo_item_id_url ON testing_url (todo_item_id, url);