create table todo_items
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_urls varchar(255)
);

create table pr_url
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_item_id  int not null,
    url varchar(255) not null
);

alter table pr_url
    add constraint fk_todo_items_on_library foreign key (todo_item_id) references todo_items (id);